server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: fintech-app
    static_configs:
      - targets:
          - localhost
        labels:
          service: fintech-api
          env: dev
          region: ru
          event_type: auth_login
          __path__: /var/log/fintech/app*.log
